# Generated by Django 3.1.7 on 2022-02-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=225)),
                ('nom', models.CharField(max_length=225)),
                ('dci1', models.CharField(max_length=225)),
                ('dosage1', models.CharField(max_length=225)),
                ('unite_dosage1', models.CharField(max_length=225)),
                ('forme', models.CharField(max_length=225)),
                ('presentation', models.CharField(max_length=225)),
                ('ppv', models.FloatField()),
                ('ph', models.CharField(max_length=225)),
                ('prix_br', models.FloatField()),
                ('principe_genetique', models.FloatField()),
                ('taux_remboursement', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicaments',
                'verbose_name_plural': 'Medicamentss',
            },
        ),
    ]
