# Generated by Django 3.1.7 on 2022-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaments',
            name='ppv',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='medicaments',
            name='principe_genetique',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='medicaments',
            name='prix_br',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='medicaments',
            name='taux_remboursement',
            field=models.CharField(max_length=225),
        ),
    ]
