# Generated by Django 3.1.7 on 2022-02-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medocapi', '0002_auto_20220208_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaments',
            options={'ordering': ('nom',), 'verbose_name': 'Medicaments', 'verbose_name_plural': 'Medicamentss'},
        ),
    ]
