# Generated by Django 3.1.7 on 2022-02-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medocapi', '0003_auto_20220216_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
                ('image', models.FileField(upload_to='category/')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
    ]
